name: Test workflow

on:
  push:
    branches:
      - 'bugfix/**'

jobs:
  test:
    container:
      image: vali0/node-grunt-gulp:8.9.4

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Clone repo
        run: |
          git clone https://Trimud:${{ secrets.GITHUB_TOKEN }}@github.com/Trimud/osf-jira-webhooks.git
          cd osf-jira-webhooks
          ls -la
      - name: Run test script
        run: |
          npm i
          npm test
