name: Test workflow

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    container:
      image: vali0/node-grunt-gulp:8.9.4

    runs-on: ubuntu-latest

    steps:
      - name: Log files
        run: ls -la
      - name: Install dependencies
        run: npm i
      - name: Run test script
        run: npm test
