name: Test workflow

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    container:
      image: vali0/node-grunt-gulp:8.9.4

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: |
          # git clone git-clone yboev$ git clone https://Trimud:49c7e92260790c3b2ee6e7df21753245222eab18@github.com/Trimud/osf-jira-webhooks.git
          ${{ secrets.GITHUB_TOKEN }}
          npm i
          npm test
