name: Test workflow

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    container:
      image: vali0/node-grunt-gulp:8.9.4

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: |
          npm i
          npm test
